# Gradle
org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false

# Mod Versions
mod_version=1.2.2

# Minecraft / NeoForge
minecraft_version=1.21.1
neoforge_version=21.1.233
neoforge_range=[21.1.0,)
loader_range=[4,)
minecraft_range=[1.21.1,1.21.2)

# Parchment mappings for 1.21.1
parchment_minecraft=1.21.1
parchment_version=2024.11.17

# Create Dependency Version (1.21.1 NeoForge)
create_version=6.0.10
